# Generated by Django 4.1 on 2022-08-13 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_rename_title_item_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='title',
        ),
    ]
