# Generated by Django 4.1 on 2022-08-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_rename_name_item_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='content',
            field=models.TextField(default='Something'),
        ),
    ]
