# Generated by Django 4.1 on 2022-08-13 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0007_alter_item_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='content',
            new_name='contents',
        ),
    ]
